export 'package:heart/screens/newAlarm.dart';
export 'package:heart/screens/login.dart';
export 'package:heart/screens/register.dart';
export 'package:heart/screens/new_record.dart';
export 'package:heart/screens/alerts.dart';
export 'package:heart/screens/news.dart';
export 'package:heart/screens/records.dart';
export 'package:heart/screens/resume.dart';
export 'package:heart/screens/home.dart';
